substitutions:
  hostname: "esp-time-lapse"

esphome:
  name: ${hostname}
  friendly_name: ESP Time Lapse Camera
  build_path: /Users/mmichon/.esphome/build/${hostname}

esp32:
  board: seeed_xiao_esp32s3
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 10.0.0.77

api:
  encryption:
    key: !secret api_encryption_key

captive_portal:
logger:
ota:
  - platform: esphome

web_server:
  port: 80

switch:
  - platform: restart
    name: "Restart"

time:
  - platform: homeassistant
    id: homeassistant_time

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

esp32_camera:
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  name: ESP Time Lapse Camera
  max_framerate: 10 fps
  idle_framerate: 0.1 fps
  resolution: 800x600
