substitutions:
  hostname: espalarm

esphome:
  name: ${hostname}
  platform: ESP8266
  board: d1_mini # pinout https://m.media-amazon.com/images/I/71d6+P4PUzL._SL1067_.jpg

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
logger:
ota:
web_server:

output:
  - platform: esp8266_pwm
    pin: D2
    id: rtttl_out

rtttl:
  output: rtttl_out

api:
  services:
    - service: sound_alarm
      then:
        - rtttl.play: "siren:d=8,o=8,b=100:b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e,b,e"
    - service: stop_alarm
      then:
        - rtttl.stop
