substitutions:
  hostname: espgaragemotion

esphome:
  name: ${hostname}
  platform: ESP8266
  board: d1_mini # pinout https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
captive_portal:
logger:
ota:
  platform: esphome
web_server:

switch:
  - platform: restart
    name: "${hostname} Restart"

status_led:
  pin:
    number: D4
    inverted: true

binary_sensor:
  - platform: gpio
    name: "Garage Motion Sensor"
    id: garage_motion_sensor
    pin: D1
    device_class: motion
    # filters:
    #   - delayed_off: 120s
    publish_initial_state: true
