substitutions:
  hostname: "espdesk"
  low_light_level: "5"

esphome:
  name: ${hostname}
  friendly_name: Desk Controller

esp8266:
  board: d1_mini # pinout https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 15min

api:
captive_portal:
logger:
ota:
  platform: esphome
web_server:

status_led:
  pin:
    number: D4
    inverted: true

# https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
# ok: 1, 2, 5, 6, 7

i2c: # for temperature sensor
  scl: D1
  sda: D2
  scan: true
  id: bus_a

sensor:
  - platform: sht3xd
    temperature:
      name: "In-law Temperature"
      # filters:
      #   - offset: -2.7 # -5ºF
    humidity:
      name: "In-law Humidity"
    address: 0x44
    update_interval: 60s

  - platform: adc
    pin: A0
    name: "In-law Light Level"
    id: desk_light_level
    update_interval: 1s
    unit_of_measurement: "%"
    filters:
      - multiply: 100 # to convert to %
      - sliding_window_moving_average:
          send_every: 60

binary_sensor:
  - platform: gpio
    name: "Desk Motion Sensor"
    id: desk_motion_sensor
    pin: D7
    device_class: motion
    filters:
      - delayed_off: 120s

  - platform: template
    name: "Desk Is Dark"
    lambda: |-
      if (id(desk_light_level).state > ${low_light_level}) {
        return false;
      } else {
        return true;
      }

  - platform: homeassistant
    entity_id: binary_sensor.in_law_occupancy
    id: desk_occupancy
    internal: true

switch:
  - platform: restart
    name: "${hostname} Restart"

  - platform: gpio
    id: desk_up_button
    name: "Desk Up Button"
    pin: D5
    restore_mode: ALWAYS_OFF
    internal: true
    interlock: &desk_buttons [desk_up_button, desk_down_button]

  - platform: gpio
    id: desk_down_button
    name: "Desk Down Button"
    pin: D6
    restore_mode: ALWAYS_OFF
    internal: true
    interlock: *desk_buttons


  # Desk Raised switch with occupancy check
  # Prevents desk movement if desk_occupancy sensor is not active
  # If occupancy not detected, reverts optimistic state change and sends notification
  - platform: template
    name: "Desk Raised"
    id: desk_raised
    icon: "mdi:desk"
    optimistic: true
    restore_mode: DISABLED
    turn_on_action:
      - lambda: |-
          // Check if sensor is available and on
          bool sensor_available = id(desk_occupancy).has_state();
          bool occupancy_detected = sensor_available && id(desk_occupancy).state;

          if (!sensor_available) {
            // Sensor unavailable - throttle warnings to once per 5 minutes
            if ((millis() - id(last_notification_millis)) > 300000) {
              id(last_notification_millis) = millis();
              ESP_LOGW("main", "Unable to raise desk: in-law occupancy sensor unavailable");
              // Revert state
              id(desk_raised).publish_state(false);
              // Send notification if API connected
              id(notify_desk_error_unavailable).execute();
            } else {
              // Just revert state without logging/notifying
              id(desk_raised).publish_state(false);
            }
            return;
          }

          if (!occupancy_detected) {
            // Occupancy not detected - throttle warnings to once per 5 minutes
            if ((millis() - id(last_notification_millis)) > 300000) {
              id(last_notification_millis) = millis();
              ESP_LOGW("main", "Unable to raise desk: in-law occupancy not detected");
              // Revert state
              id(desk_raised).publish_state(false);
              // Send notification if API connected
              id(notify_desk_error_no_occupancy).execute();
            } else {
              // Just revert state without logging/notifying
              id(desk_raised).publish_state(false);
            }
            return;
          }

          // Occupancy detected - proceed with raising desk
          id(desk_up_button).turn_on();
      - delay: 16.3s
      - switch.turn_off: desk_up_button
      - delay: .5s
      - switch.turn_on: desk_down_button
      - delay: .5s
      - switch.turn_off: desk_down_button

    turn_off_action:
      - lambda: |-
          // Check if sensor is available and on
          bool sensor_available = id(desk_occupancy).has_state();
          bool occupancy_detected = sensor_available && id(desk_occupancy).state;

          if (!sensor_available) {
            // Sensor unavailable - throttle warnings to once per 5 minutes
            if ((millis() - id(last_notification_millis)) > 300000) {
              id(last_notification_millis) = millis();
              ESP_LOGW("main", "Unable to lower desk: in-law occupancy sensor unavailable");
              // Revert state
              id(desk_raised).publish_state(true);
              // Send notification if API connected
              id(notify_desk_error_unavailable).execute();
            } else {
              // Just revert state without logging/notifying
              id(desk_raised).publish_state(true);
            }
            return;
          }

          if (!occupancy_detected) {
            // Occupancy not detected - throttle warnings to once per 5 minutes
            if ((millis() - id(last_notification_millis)) > 300000) {
              id(last_notification_millis) = millis();
              ESP_LOGW("main", "Unable to lower desk: in-law occupancy not detected");
              // Revert state
              id(desk_raised).publish_state(true);
              // Send notification if API connected
              id(notify_desk_error_no_occupancy).execute();
            } else {
              // Just revert state without logging/notifying
              id(desk_raised).publish_state(true);
            }
            return;
          }

          // Occupancy detected - proceed with lowering desk
          id(desk_down_button).turn_on();
      - delay: 14.8s
      - switch.turn_off: desk_down_button
      - delay: .5s
      - switch.turn_on: desk_up_button
      - delay: .5s
      - switch.turn_off: desk_up_button

cover:
  - platform: time_based
    name: "Desk Height"

    open_action:
      - switch.turn_on: desk_up_button
    open_duration: 16.3s

    close_action:
      - switch.turn_on: desk_down_button
    close_duration: 15.2s

    stop_action:
      - switch.turn_off: desk_up_button
      - switch.turn_off: desk_down_button

globals:
  - id: last_notification_millis
    type: unsigned long
    restore_value: false
    initial_value: '0'

script:
  - id: notify_desk_error_unavailable
    then:
      - if:
          condition:
            api.connected:
          then:
            - homeassistant.service:
                service: notify.all_mike_devices
                data_template:
                  message: "‼️ Unable to set desk height because in-law occupancy sensor is unavailable."

  - id: notify_desk_error_no_occupancy
    then:
      - if:
          condition:
            api.connected:
          then:
            - homeassistant.service:
                service: notify.all_mike_devices
                data_template:
                  message: "‼️ Unable to set desk height because in-law occupancy is not detected."