substitutions:
  esp_hostname: espinlaw

esphome:
  name: ${esp_hostname}
  platform: ESP8266
  board: d1_mini # pinout https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
logger:
ota:
web_server:

status_led:
  pin:
    number: D4
    inverted: true

remote_transmitter:
  - id: ir_transmitter
    pin: D8
    carrier_duty_percent: 50%

# https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
# ok: 1, 2, 5, 6, 7
binary_sensor:
  - platform: gpio
    name: "In-law Motion Sensor"
    id: inlaw_motion_sensor
    pin: D7
    device_class: motion
    filters:
      - delayed_off: 120s

i2c:
  scl: D1
  sda: D2
  scan: true
  id: bus_a

sensor:
  - platform: sht3xd
    temperature:
      name: "In-law Temperature"
      filters:
        - offset: -2.7 # -5ºF
    humidity:
      name: "In-law Humidity"
    address: 0x44
    update_interval: 60s

switch:
  - platform: restart
    name: "${esp_hostname} Restart"

  - platform: gpio
    id: desk_up_button
    name: "Desk Up Button"
    pin: D5
    restore_mode: ALWAYS_OFF
    internal: true
    interlock: &interlock [desk_up_button, desk_down_button]
  - platform: gpio
    id: desk_down_button
    name: "Desk Down Button"
    pin: D6
    restore_mode: ALWAYS_OFF
    internal: true
    interlock: *interlock

  - platform: template
    name: "Desk Raised"
    id: desk_raised
    icon: "mdi:desk"
    optimistic: true
    restore_state: true
    turn_on_action:
      - switch.turn_on: desk_up_button
      - delay: 16.3s
      - switch.turn_off: desk_up_button
      - delay: .5s
      - switch.turn_on: desk_down_button
      - delay: .5s
      - switch.turn_off: desk_down_button

    turn_off_action:
      - switch.turn_on: desk_down_button
      - delay: 14.8s
      - switch.turn_off: desk_down_button
      - delay: .5s
      - switch.turn_on: desk_up_button
      - delay: 1s
      - switch.turn_off: desk_up_button
# cover:
#   - platform: time_based
#     name: "Desk Height"

#     open_action:
#       - switch.turn_on: desk_up_button
#     open_duration: 16.3s

#     close_action:
#       - switch.turn_on: desk_down_button
#     close_duration: 15.2s

#     stop_action:
#       - switch.turn_off: desk_up_button
#       - switch.turn_off: desk_down_button

api:
  services:
    - service: hk_tv
      then:
        - remote_transmitter.transmit_pronto:
            transmitter_id: ir_transmitter
            data: "0000 006D 0021 0000 0017 0014 0017 0014 0017 0014 0017 0014 0017 0014 0017 0014 0018 0014 0017 0040 0017 0014 0017 0014 0017 0014 0017 0014 0017 0040 0017 0040 0017 0040 0017 0014 0017 003F 0018 003F 0018 0013 0018 0013 0018 003F 0018 0013 0018 003F 0018 003F 0018 0013 0018 0013 0018 003F 0018 003F 0018 0013 0018 003F 0018 0013 0018 0013 0018 06C3"
    - service: tv_power
      then:
        - remote_transmitter.transmit_pioneer:
            transmitter_id: ir_transmitter
            rc_code_1: 0x2008
    - service: tv_netflix
      then:
        - remote_transmitter.transmit_pioneer:
            transmitter_id: ir_transmitter
            rc_code_1: 0x20EB
