substitutions:
  hostname: esplora-recv

esphome:
  name: ${hostname}
  platform: ESP32
  board: ttgo-lora32-v1
  includes:
    - lora_recv.h
  libraries:
    - "LoRa"
    - "SPI"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
captive_portal:
logger:
ota:
web_server:

lora:
  - platform: sx127x
    id: lora_12
    sync_word: 0x34
    di0_pin: GPIO26
    rst_pin: GPIO14
    cs_pin: GPIO18
    band: 868MHZ

spi:
  clk_pin: GPIO5
  mosi_pin: GPIO27
  miso_pin: GPIO19
# sensor:
#   - platform: wifi_signal
#     name: "Lora 2 WiFi Signal Sensor"
#     update_interval: 5s
#   - platform: template
#     name: "Lora 2 Showing Lora1 WiFi Signal Sensor"
#     receive_from_lora: true
#     lora_name: lora1_wifi_signal_sensor
#     update_interval: never
#     unit_of_measurement: "dB"
#     icon: "mdi:wifi"
#   - platform: lora
#     rssi:
#       name: "Lora2 Last RSSI"
#       update_interval: 5s
#     snr:
#       name: "Lora2 Last SNR"
#       update_interval: 5s

# switch:
#   - platform: template
#     name: "Lora 2 Showing Lora1 Switch Binary Sensor 1"
#     receive_from_lora: true
#     lora_name: switch_binary_sensor_1

# binary_sensor:
#   - platform: template
#     name: "Lora 2 Showing Lora 1 Binary Sensor"
#     lora_name: lora_1_binary_sensor
#     receive_from_lora: true

# text_sensor:
#   - platform: template
#     name: "Lora 2 Showing Lora 1 Wifi SSID"
#     lora_name: lora_1_wifi_ssid
#     receive_from_lora: true
