substitutions:
  location: Office
  hostname: espoffice

esphome:
  name: ${hostname}
  platform: ESP8266
  board: d1_mini # pinout https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
captive_portal:
logger:
ota:
web_server:

switch:
  - platform: restart
    name: "${hostname} Restart"

status_led:
  pin:
    number: D4
    inverted: true

sensor:
  # DHT11
  - platform: dht
    pin: D1
    temperature:
      name: "${location} Temperature"
      filters:
        - offset: -6.2 # -4ºF
    humidity:
      name: "${location} Humidity"
    update_interval: 60s
