substitutions:
  hostname: espinlaw
  low_light_level: "5"

esphome:
  name: ${hostname}
  friendly_name: Desk Controller
  platform: ESP8266
  board: d1_mini # pinout https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
  on_boot:
    priority: -100
    then:
      - lambda: |-
          id(last_notification_millis) = 0;

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
captive_portal:
logger:
ota:
  platform: esphome
web_server:

status_led:
  pin:
    number: D4
    inverted: true

# https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
# ok: 1, 2, 5, 6, 7

i2c: # for temperature sensor
  scl: D1
  sda: D2
  scan: true
  id: bus_a

sensor:
  - platform: sht3xd
    temperature:
      name: "In-law Temperature"
      # filters:
      #   - offset: -2.7 # -5ºF
    humidity:
      name: "In-law Humidity"
    address: 0x44
    update_interval: 60s

  - platform: adc
    pin: A0
    name: "In-law Light Level"
    id: in_law_light_level
    update_interval: 1s
    unit_of_measurement: "%"
    filters:
      - multiply: 100 # to convert to %
      - sliding_window_moving_average:
          send_every: 60

binary_sensor:
  - platform: gpio
    name: "In-law Motion Sensor"
    id: inlaw_motion_sensor
    pin: D7
    device_class: motion
    filters:
      - delayed_off: 120s

  - platform: template
    name: "In-law Is Dark"
    lambda: |-
      if (id(in_law_light_level).state > ${low_light_level}) {
        return false;
      } else {
        return true;
      }

switch:
  - platform: restart
    name: "${hostname} Restart"

  - platform: gpio
    id: desk_up_button
    name: "Desk Up Button"
    pin: D5
    restore_mode: ALWAYS_OFF
    internal: true
    interlock: &desk_buttons [desk_up_button, desk_down_button]

  - platform: gpio
    id: desk_down_button
    name: "Desk Down Button"
    pin: D6
    restore_mode: ALWAYS_OFF
    internal: true
    interlock: *desk_buttons


  - platform: template
    name: "Desk Raised"
    id: desk_raised
    icon: "mdi:desk"
    optimistic: true
    restore_mode: DISABLED
    turn_on_action:
      - if:
          condition:
            binary_sensor.is_on: inlaw_motion_sensor
          then:
            - switch.turn_on: desk_up_button
            - delay: 16.3s
            - switch.turn_off: desk_up_button
            - delay: .5s
            - switch.turn_on: desk_down_button
            - delay: .5s
            - switch.turn_off: desk_down_button
          else:
            - lambda: |-
                // Revert the optimistic state change since operation is blocked
                id(desk_raised).publish_state(false);
                // Throttle notifications to once per 5 minutes
                if ((millis() - id(last_notification_millis)) > 300000) {
                  id(last_notification_millis) = millis();
                  ESP_LOGE("desk", "Desk operation blocked: occupancy not detected");
                }

    turn_off_action:
      - if:
          condition:
            binary_sensor.is_on: inlaw_motion_sensor
          then:
            - switch.turn_on: desk_down_button
            - delay: 14.8s
            - switch.turn_off: desk_down_button
            - delay: .5s
            - switch.turn_on: desk_up_button
            - delay: 1s
            - switch.turn_off: desk_up_button
          else:
            - lambda: |-
                // Revert the optimistic state change since operation is blocked
                id(desk_raised).publish_state(true);
                // Throttle notifications to once per 5 minutes
                if ((millis() - id(last_notification_millis)) > 300000) {
                  id(last_notification_millis) = millis();
                  ESP_LOGE("desk", "Desk operation blocked: occupancy not detected");
                }

cover:
  - platform: time_based
    name: "Desk Height"

    open_action:
      - if:
          condition:
            binary_sensor.is_on: inlaw_motion_sensor
          then:
            - switch.turn_on: desk_up_button
          else:
            - lambda: |-
                // Throttle notifications to once per 5 minutes
                if ((millis() - id(last_notification_millis)) > 300000) {
                  id(last_notification_millis) = millis();
                  ESP_LOGE("desk", "Desk operation blocked: occupancy not detected");
                }
    open_duration: 16.3s

    close_action:
      - if:
          condition:
            binary_sensor.is_on: inlaw_motion_sensor
          then:
            - switch.turn_on: desk_down_button
          else:
            - lambda: |-
                // Throttle notifications to once per 5 minutes
                if ((millis() - id(last_notification_millis)) > 300000) {
                  id(last_notification_millis) = millis();
                  ESP_LOGE("desk", "Desk operation blocked: occupancy not detected");
                }
    close_duration: 15.2s

    stop_action:
      - switch.turn_off: desk_up_button
      - switch.turn_off: desk_down_button

globals:
  - id: last_notification_millis
    type: unsigned long
    restore_value: false
    initial_value: '0'
