#!/bin/bash
# Script to diagnose and fix HomeKit streaming issues in Scrypted

echo "=== Scrypted HomeKit Camera Diagnostic ==="
echo ""

# Check if we can access Scrypted
echo "1. Checking Scrypted container status..."
ssh root@nuc.local "pct exec 106 -- docker ps | grep scrypted"

echo ""
echo "2. Checking HomeKit plugin status..."
ssh root@nuc.local "pct exec 106 -- docker exec scrypted ps aux | grep homekit"

echo ""
echo "3. Checking for active ffmpeg processes (streaming)..."
ssh root@nuc.local "pct exec 106 -- docker exec scrypted ps aux | grep ffmpeg"

echo ""
echo "4. Checking network connectivity..."
ssh root@nuc.local "pct exec 106 -- docker exec scrypted curl -s -k https://127.0.0.1:10443/ 2>&1 | head -1"

echo ""
echo "=== Common HomeKit Streaming Issues ==="
echo ""
echo "For cameras showing 'no response' in HomeKit, check the following in Scrypted web UI:"
echo ""
echo "1. Codec Settings:"
echo "   - HomeKit requires H.264, NOT H.265/HEVC"
echo "   - Go to each camera's settings in Scrypted"
echo "   - Check 'Video Codec' or 'Stream Codec'"
echo "   - Ensure it's set to H.264"
echo ""
echo "2. Resolution Settings:"
echo "   - High resolutions (4K) can cause timeouts"
echo "   - Try reducing to 1080p or 720p for HomeKit"
echo "   - Check 'Resolution' or 'Stream Resolution' in camera settings"
echo ""
echo "3. Bitrate Settings:"
echo "   - High bitrates can cause network timeouts"
echo "   - Try reducing bitrate to 2000-4000 kbps"
echo "   - Check 'Bitrate' in camera settings"
echo ""
echo "4. Prebuffer Settings:"
echo "   - Go to Prebuffer Mixin plugin settings"
echo "   - Ensure prebuffer is enabled for cameras"
echo "   - Check prebuffer duration (5-10 seconds recommended)"
echo ""
echo "5. HomeKit Plugin Settings:"
echo "   - Go to HomeKit plugin settings"
echo "   - Check 'Video Codec' is set to H.264"
echo "   - Check 'Video Resolution' is appropriate (1080p max recommended)"
echo "   - Check 'Video Bitrate' is reasonable (2000-4000 kbps)"
echo ""
echo "6. RTSP Stream Settings:"
echo "   - Check RTSP stream URL is correct"
echo "   - Verify stream is accessible"
echo "   - Check for stream timeouts"
echo ""
echo "=== To Fix Issues ==="
echo ""
echo "Access Scrypted web UI at: https://10.0.0.53:10443"
echo ""
echo "For 'Wide Entry Camera' and 'Entry Camera':"
echo "1. Go to each camera's settings"
echo "2. Check Video Codec - must be H.264"
echo "3. Check Resolution - try 1080p or lower"
echo "4. Check Bitrate - try 2000-4000 kbps"
echo "5. Go to HomeKit plugin settings"
echo "6. Ensure HomeKit video codec is H.264"
echo "7. Restart the cameras or Scrypted service"
echo ""
